# Libraries

In [6]:
import pandas as pd 
import numpy as np

## Train and test dataset

In [8]:
train = pd.read_csv("store-sales-time-series-forecasting/train.csv")
train.head()
test = pd.read_csv("store-sales-time-series-forecasting/test.csv")
test.head()

        id        date  store_nbr      family  onpromotion
0  3000888  2017-08-16          1  AUTOMOTIVE            0
1  3000889  2017-08-16          1   BABY CARE            0
2  3000890  2017-08-16          1      BEAUTY            2
3  3000891  2017-08-16          1   BEVERAGES           20
4  3000892  2017-08-16          1       BOOKS            0

In [42]:
train.info()
train.isna().sum()
print(f"\nTotal sum: {round(np.sum(train["sales"]),2)}")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000888 entries, 0 to 3000887
Data columns (total 6 columns):
 #   Column       Dtype
---  ------       -----
 0   id           int64
 1   date         object
 2   store_nbr    int64
 3   family       object
 4   sales        float64
 5   onpromotion  int64
dtypes: float64(1), int64(3), object(2)
memory usage: 137.4+ MB

Total sum: 1073644952.2

In [40]:
train.groupby("family", as_index=False)["sales"].sum().round().sort_values("sales", ascending=False).head(10)

           family        sales
12      GROCERY I  343462735.0
3       BEVERAGES  216954486.0
30        PRODUCE  122704685.0
7        CLEANING   97521289.0
8           DAIRY   64487709.0
5    BREAD/BAKERY   42133946.0
28        POULTRY   31876004.0
24          MEATS   31086468.0
25  PERSONAL CARE   24592051.0
9            DELI   24110322.0

In [14]:
test.info()
test.isna().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28512 entries, 0 to 28511
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           28512 non-null  int64
 1   date         28512 non-null  object
 2   store_nbr    28512 non-null  int64
 3   family       28512 non-null  object
 4   onpromotion  28512 non-null  int64
dtypes: int64(3), object(2)
memory usage: 1.1+ MB

id             0
date           0
store_nbr      0
family         0
onpromotion    0
dtype: int64

## Other files